[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "client/dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  functions = "netlify/functions"
  envFile = ".env"
