import React, { useEffect, useMemo, useState } from "react";
import { supabase } from "../../supabaseClient";
import { mapDbToUi } from "../../utils/dbMapper";

const toUi = (record) => ({ ...mapDbToUi(record), contactPerson: record.contact_person, email: record.email, phone: record.phone_number, gst: record.gst_number });

export default function CompanyMasterList({ onSelectCompany }) {
  const [companies, setCompanies] = useState([]); const [searchQuery, setSearchQuery] = useState(""); const [filterStatus, setFilterStatus] = useState("All");
  const [showAddForm, setShowAddForm] = useState(false); const [editing, setEditing] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const [newName, setNewName] = useState(""); const [newCin, setNewCin] = useState(""); const [newGroup, setNewGroup] = useState(""); const [newStatus, setNewStatus] = useState("Active");

  const loadCompanies = async () => { setLoading(true); const { data, error: loadError } = await supabase.from("customers").select("*").order("company_name"); if (loadError) setError(loadError.message); else setCompanies((data || []).map(toUi)); setLoading(false); };
  useEffect(() => { loadCompanies(); }, []);

  const handleAddCompany = async (event) => { event.preventDefault(); setError(""); const { data, error: insertError } = await supabase.from("customers").insert([{ company_name: newName, cin: newCin || null, parent_group: newGroup || null, status: newStatus }]).select().single(); if (insertError) return setError(insertError.message); setCompanies((items) => [...items, toUi(data)]); setNewName(""); setNewCin(""); setNewGroup(""); setShowAddForm(false); };
  const saveProfile = async (event) => { event.preventDefault(); if (!editing) return; setError(""); const { data, error: updateError } = await supabase.from("customers").update({ company_name: editing.name, cin: editing.cin || null, parent_group: editing.group || null, status: editing.status, contact_person: editing.contactPerson || null, email: editing.email || null, phone_number: editing.phone || null, gst_number: editing.gst || null }).eq("id", editing.id).select().single(); if (updateError) return setError(updateError.message); const updated = toUi(data); setCompanies((items) => items.map((item) => item.id === updated.id ? updated : item)); setEditing(null); };

  const filtered = useMemo(() => companies.filter((company) => { const term = searchQuery.toLowerCase(); return (company.name?.toLowerCase().includes(term) || company.cin?.toLowerCase().includes(term) || company.group?.toLowerCase().includes(term)) && (filterStatus === "All" || company.status === filterStatus); }), [companies, searchQuery, filterStatus]);
  const stats = useMemo(() => ({ active: companies.filter((item) => item.status === "Active").length, groups: new Set(companies.map((item) => item.group).filter(Boolean)).size, missingCin: companies.filter((item) => !item.cin).length }), [companies]);

  return <div className="p-6 bg-slate-950 min-h-screen text-slate-100 font-sans"><style>{`.field{width:100%;background:#020617;border:1px solid #1e293b;border-radius:6px;padding:9px 10px;font-size:12px;color:#e2e8f0;outline:none}.field:focus{border-color:#6366f1}.panel{background:#0f172a;border:1px solid #1e293b;border-radius:12px;padding:20px}.label{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em;color:#94a3b8}`}</style>
    <header className="bg-slate-900 border border-slate-800 rounded-xl p-5 mb-6 flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><span className="text-[10px] font-bold uppercase tracking-widest text-indigo-400 bg-indigo-950/60 px-2.5 py-0.5 rounded-full border border-indigo-900">Corporate registry</span><h1 className="text-2xl font-black mt-2">Companies Portfolio Master</h1><p className="text-xs text-slate-400 mt-1">Live customer directory and compliance profile view.</p></div><button onClick={() => setShowAddForm(!showAddForm)} className="px-4 py-2.5 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-xs font-bold uppercase">{showAddForm ? "Close form" : "Add new company"}</button></header>
    {error && <div className="mb-5 p-3 bg-rose-950 border border-rose-900 text-rose-300 rounded-lg text-xs">{error}</div>}
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-6"><Metric label="Total companies" value={companies.length} tone="indigo" /><Metric label="Active profiles" value={stats.active} tone="emerald" /><Metric label="Corporate groups" value={stats.groups} tone="amber" /><Metric label="CIN details missing" value={stats.missingCin} tone="rose" /></div>
    {showAddForm && <form onSubmit={handleAddCompany} className="mb-6 panel"><h2 className="label mb-4">Create company profile</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Field value={newName} onChange={setNewName} placeholder="Company name" required /><Field value={newCin} onChange={setNewCin} placeholder="CIN" /><Field value={newGroup} onChange={setNewGroup} placeholder="Parent group" /><StatusSelect value={newStatus} onChange={setNewStatus} /></div><button className="mt-4 w-full bg-emerald-600 hover:bg-emerald-700 py-2.5 rounded text-xs font-bold uppercase">Save profile</button></form>}
    {editing && <form onSubmit={saveProfile} className="mb-6 panel border-indigo-800"><div className="flex justify-between mb-4"><div><h2 className="label text-indigo-300">Complete / edit company profile</h2><p className="text-[11px] text-slate-400 mt-1">Saved directly to Supabase.</p></div><button type="button" onClick={() => setEditing(null)} className="text-xs text-slate-400">Close</button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Field value={editing.name || ""} onChange={(value) => setEditing({ ...editing, name: value })} placeholder="Company name" required /><Field value={editing.cin || ""} onChange={(value) => setEditing({ ...editing, cin: value })} placeholder="CIN" /><Field value={editing.gst || ""} onChange={(value) => setEditing({ ...editing, gst: value })} placeholder="GST number" /><Field value={editing.group || ""} onChange={(value) => setEditing({ ...editing, group: value })} placeholder="Parent group" /><Field value={editing.contactPerson || ""} onChange={(value) => setEditing({ ...editing, contactPerson: value })} placeholder="Contact person" /><Field value={editing.email || ""} onChange={(value) => setEditing({ ...editing, email: value })} placeholder="Email" type="email" /><Field value={editing.phone || ""} onChange={(value) => setEditing({ ...editing, phone: value })} placeholder="Phone number" /><StatusSelect value={editing.status || "Active"} onChange={(value) => setEditing({ ...editing, status: value })} /></div><button className="mt-4 w-full bg-indigo-600 hover:bg-indigo-700 py-2.5 rounded text-xs font-bold uppercase">Save company profile</button></form>}
    <section className="panel overflow-hidden"><div className="p-4 border-b border-slate-800 flex flex-col lg:flex-row gap-3 lg:justify-between"><div><h2 className="label">Company intelligence directory</h2><p className="text-[11px] text-slate-500 mt-1">Showing {filtered.length} of {companies.length} entities</p></div><div className="flex gap-2"><input value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} className="field sm:w-64" placeholder="Search company, CIN, group..." /><select value={filterStatus} onChange={(event) => setFilterStatus(event.target.value)} className="field sm:w-32"><option>All</option><option>Active</option><option>Alert</option><option>Inactive</option></select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-slate-950 text-slate-400 uppercase"><tr><th className="p-4">Company & registration</th><th className="p-4">Group / contact</th><th className="p-4">Compliance identifiers</th><th className="p-4">Profile health</th><th className="p-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-800">{loading ? <tr><td colSpan="5" className="p-8 text-center text-slate-500">Loading company portfolio...</td></tr> : filtered.length ? filtered.map((company) => <tr key={company.id} className="hover:bg-slate-800/40"><td className="p-4"><p className="font-bold">{company.name || "Unnamed company"}</p><button onClick={() => setEditing(company)} className={company.cin ? "font-mono text-[11px] text-indigo-300 mt-1" : "font-mono text-[11px] text-amber-400 mt-1 underline"}>{company.cin || "Add CIN"}</button></td><td className="p-4"><p>{company.group || "Independent entity"}</p><button onClick={() => setEditing(company)} className="text-[11px] text-slate-500 mt-1 hover:text-indigo-300">{company.contactPerson || company.email || "Add contact details"}</button></td><td className="p-4"><button onClick={() => setEditing(company)} className="hover:text-indigo-300">GST: {company.gst || "Add GST"}</button><p className="text-[11px] text-slate-500 mt-1">{company.phone || company.email || "No contact channel"}</p></td><td className="p-4"><Status value={company.status} /><p className="text-[10px] text-slate-500 mt-2">{company.pendingTasks || 0} workflow tasks</p></td><td className="p-4 text-right"><button onClick={() => setEditing(company)} className="px-3 py-1.5 bg-amber-600 hover:bg-amber-700 rounded text-[10px] font-bold">EDIT</button><button onClick={() => onSelectCompany(company)} className="ml-2 px-3 py-1.5 bg-slate-800 hover:bg-indigo-600 rounded text-[10px] font-bold">OPEN</button></td></tr>) : <tr><td colSpan="5" className="p-8 text-center text-slate-500">No companies match the current search.</td></tr>}</tbody></table></div></section>
  </div>;
}
function Field({ value, onChange, ...props }) { return <input value={value} onChange={(event) => onChange(event.target.value)} className="field" {...props} />; }
function StatusSelect({ value, onChange }) { return <select value={value} onChange={(event) => onChange(event.target.value)} className="field"><option>Active</option><option>Alert</option><option>Inactive</option></select>; }
function Metric({ label, value, tone }) { const colors = { indigo: "border-l-indigo-500", emerald: "border-l-emerald-500", amber: "border-l-amber-500", rose: "border-l-rose-500" }; return <div className={`bg-slate-900 border border-slate-800 border-l-4 rounded-xl p-4 ${colors[tone]}`}><p className="label">{label}</p><p className="text-2xl font-black mt-1">{value}</p></div>; }
function Status({ value }) { const colors = value === "Active" ? "bg-emerald-950 text-emerald-300 border-emerald-900" : value === "Alert" ? "bg-amber-950 text-amber-300 border-amber-900" : "bg-slate-800 text-slate-400 border-slate-700"; return <span className={`px-2 py-1 rounded border text-[10px] font-bold ${colors}`}>{value || "Unknown"}</span>; }
