import React, { useEffect, useMemo, useState } from "react";
import { supabase } from "../../supabaseClient";

const CLOSED = new Set(["Completed", "Closed", "Cancelled"]);
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });

export default function DashboardHome() {
  const [data, setData] = useState({ customers: [], employees: [], tasks: [], cases: [], invoices: [], taskLogs: [], taxLogs: [], reminderLogs: [] });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = async () => {
    setLoading(true); setError("");
    const [customers, employees, tasks, cases, invoices, taskLogs, taxLogs, reminderLogs] = await Promise.all([
      supabase.from("customers").select("id,company_name").eq("status", "Active"),
      supabase.from("employees").select("id,full_name,active_tasks,max_capacity,employment_status").order("full_name"),
      supabase.from("tasks").select("id,title,created_at,status,workstream,assign_to_customer").order("created_at", { ascending: false }),
      supabase.from("legal_cases").select("id,status"),
      supabase.from("invoices").select("total_amount,paid_amount"),
      supabase.from("task_execution_logs").select("id,task_id,previous_status,next_status,note,changed_by,created_at").order("created_at", { ascending: false }).limit(100),
      supabase.from("tax_filing_logs").select("id,tax_filing_id,previous_status,next_status,note,changed_by,created_at").order("created_at", { ascending: false }).limit(100),
      supabase.from("reminder_action_logs").select("id,created_at,reminder_key,action_type,module,title,client_name,effective_due_date,action_by").order("created_at", { ascending: false }).limit(100),
    ]);
    const failures = [customers.error, employees.error, tasks.error, cases.error, invoices.error, taskLogs.error, taxLogs.error, reminderLogs.error].filter(Boolean);
    if (failures.length) setError(`${failures.map((item) => item.message).join(" · ")} ${reminderLogs.error ? "Run reminder-system-v2.sql." : ""}`);
    setData({ customers: customers.data || [], employees: employees.data || [], tasks: tasks.data || [], cases: cases.data || [], invoices: invoices.data || [], taskLogs: taskLogs.data || [], taxLogs: taxLogs.data || [], reminderLogs: reminderLogs.data || [] });
    setLoading(false);
  };

  useEffect(() => {
    load();
    const refresh = () => load();
    window.addEventListener("firmaxis:reminder-action", refresh);
    const interval = window.setInterval(load, 30000);
    return () => { window.removeEventListener("firmaxis:reminder-action", refresh); window.clearInterval(interval); };
  }, []);

  const overview = useMemo(() => {
    const currentDay = today(); const taskMap = new Map(data.tasks.map((item) => [item.id, item])); const customerMap = new Map(data.customers.map((item) => [item.id, item.company_name])); const events = [];
    data.taskLogs.filter((item) => datePart(item.created_at) === currentDay).forEach((item) => { const task = taskMap.get(item.task_id); events.push({ id: `task-${item.id}`, module: moduleOf(task?.workstream), title: task?.title || "Task progress update", detail: `${item.previous_status || "Created"} → ${item.next_status || "Updated"}${item.note ? ` · ${item.note}` : ""}`, at: item.created_at, actor: item.changed_by || "Firm user" }); });
    data.taxLogs.filter((item) => datePart(item.created_at) === currentDay).forEach((item) => events.push({ id: `tax-${item.id}`, module: "TAX", title: "Tax filing update", detail: `${item.previous_status || "Created"} → ${item.next_status || "Updated"}${item.note ? ` · ${item.note}` : ""}`, at: item.created_at, actor: item.changed_by || "Firm user" }));
    data.reminderLogs.filter((item) => datePart(item.created_at) === currentDay).forEach((item) => events.push({ id: `reminder-${item.id}`, module: item.module || "COMPLIANCE", title: item.title || "Reminder", detail: item.action_type === "snoozed" ? `Reminder snoozed to ${item.effective_due_date}` : item.action_type === "acknowledged" ? "Reminder acknowledged" : "Reminder reopened", at: item.created_at, actor: item.client_name || "Firm user" }));
    data.tasks.filter((item) => datePart(item.created_at) === currentDay).forEach((item) => events.push({ id: `new-task-${item.id}`, module: moduleOf(item.workstream), title: item.title || "New task", detail: `New task created · ${customerMap.get(item.assign_to_customer) || "No client"}`, at: item.created_at, actor: "Firm system" }));
    return { openTasks: data.tasks.filter((item) => item.title?.trim() && !CLOSED.has(item.status)), activeCases: data.cases.filter((item) => !["Closed", "Disposed"].includes(item.status)).length, outstanding: data.invoices.reduce((sum, item) => sum + Math.max(Number(item.total_amount || 0) - Number(item.paid_amount || 0), 0), 0), events: events.sort((a, b) => String(b.at).localeCompare(String(a.at))).slice(0, 30) };
  }, [data]);

  return <div className="min-h-screen bg-slate-950 p-6 text-slate-100"><style>{css}</style><header className="panel mb-6 flex flex-col gap-4 md:flex-row md:justify-between"><div><span className="tag">Firm command centre</span><h1 className="mt-2 text-2xl font-black">Operational Overview</h1><p className="mt-1 text-xs text-slate-400">Live work progress from compliance, litigation, tax, and reminder actions.</p></div><button className="button" onClick={load}>{loading ? "Refreshing…" : "Refresh dashboard"}</button></header>{error && <div className="alert">{error}</div>}<div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Active clients" value={data.customers.length} tone="emerald" /><Metric label="Open tasks" value={overview.openTasks.length} tone="indigo" /><Metric label="Active legal cases" value={overview.activeCases} tone="amber" /><Metric label="Today's activity" value={overview.events.length} tone="violet" /><Metric label="Outstanding fees" value={money.format(overview.outstanding)} tone="rose" /></div><div className="grid grid-cols-1 gap-6 xl:grid-cols-12"><section className="panel xl:col-span-8"><div className="mb-3 flex justify-between border-b border-slate-800 pb-3"><div><h2 className="heading">Today's work progress</h2><p className="hint">Reminder actions are recorded immediately and this panel refreshes every 30 seconds.</p></div><span className="count">{overview.events.length} events</span></div>{loading ? <Empty text="Loading activity…" /> : overview.events.length ? <div className="max-h-[680px] space-y-2 overflow-y-auto pr-1">{overview.events.map((event) => <article className="activity" key={event.id}><div className="flex items-center gap-2"><Badge value={event.module} /><b className="text-xs">{event.title}</b></div><p className="mt-2 text-[11px] text-slate-400">{event.detail}</p><p className="hint mt-2">{event.actor} · {formatTime(event.at)}</p></article>)}</div> : <Empty text="No work updates recorded today." />}</section><section className="panel xl:col-span-4"><h2 className="heading">Team workload snapshot</h2><p className="hint mb-4">Capacity is kept separate from the deadline calendar.</p><div className="max-h-[680px] space-y-4 overflow-y-auto pr-1">{data.employees.filter((item) => item.employment_status !== "INACTIVE").map((item) => { const capacity = Number(item.max_capacity || 10); const active = Number(item.active_tasks || 0); const percent = Math.min(100, (active / capacity) * 100); return <div key={item.id}><div className="flex justify-between text-xs"><b>{item.full_name}</b><span>{active}/{capacity}</span></div><div className="bar"><div className={percent >= 80 ? "fill high" : "fill"} style={{ width: `${percent}%` }} /></div></div>; })}</div></section></div></div>;
}
function today() { return datePart(new Date()); } function datePart(value) { return String(value || "").slice(0, 10); } function moduleOf(value) { const name = String(value || "").toUpperCase(); return name === "LITIGATION" ? "LITIGATION" : name === "TAX" ? "TAX" : "COMPLIANCE"; } function formatTime(value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Time unavailable" : date.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" }); } function Metric({ label, value, tone }) { return <div className={`metric ${tone}`}><p>{label}</p><strong>{value}</strong></div>; } function Badge({ value }) { return <span className={`badge ${String(value).toLowerCase()}`}>{value}</span>; } function Empty({ text }) { return <div className="empty">{text}</div>; }
const css = `.panel{background:#0f172a;border:1px solid #1e293b;border-radius:12px;padding:20px}.tag,.heading{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em;color:#a5b4fc}.heading{color:#94a3b8}.button{background:#1e293b;border:1px solid #334155;border-radius:7px;padding:10px 13px;font-size:11px;font-weight:800;text-transform:uppercase}.metric{background:#0f172a;border:1px solid #1e293b;border-left:4px solid #6366f1;border-radius:10px;padding:15px}.metric p,.hint{font-size:10px;color:#94a3b8}.metric strong{display:block;font-size:23px;margin-top:5px}.metric.emerald{border-left-color:#10b981}.metric.amber{border-left-color:#f59e0b}.metric.violet{border-left-color:#8b5cf6}.metric.rose{border-left-color:#f43f5e}.activity{background:#020617;border:1px solid #1e293b;border-radius:8px;padding:13px}.badge{font-size:9px;font-weight:800;padding:3px 6px;border-radius:4px}.compliance{background:#172554;color:#bfdbfe}.litigation{background:#451a03;color:#fde68a}.tax{background:#064e3b;color:#a7f3d0}.count{font-size:10px;color:#a5b4fc}.empty{border:1px dashed #334155;border-radius:8px;padding:35px;text-align:center;color:#64748b;font-size:12px}.alert{margin-bottom:14px;background:#4c0519;border:1px solid #881337;color:#fecdd3;border-radius:7px;padding:11px;font-size:12px}.bar{height:6px;background:#1e293b;border-radius:999px;margin-top:7px}.fill{height:100%;background:#10b981;border-radius:999px}.fill.high{background:#f43f5e}`;