import React, { useEffect, useMemo, useState } from "react";
import { supabase } from "../../supabaseClient";
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const CLOSED = new Set(["Completed", "Closed", "Cancelled"]);

export default function DashboardHome() {
  const [data, setData] = useState({ customers: [], tasks: [], cases: [], invoices: [], employees: [], activity: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); const [customers, tasks, cases, invoices, employees, activity] = await Promise.all([
    supabase.from("customers").select("id").eq("status", "Active"), supabase.from("tasks").select("id,title,status"), supabase.from("legal_cases").select("id,status"), supabase.from("invoices").select("total_amount,paid_amount"), supabase.from("employees").select("id,full_name,active_tasks,max_capacity,employment_status").order("full_name"), supabase.from("firm_audit_logs").select("id,created_at,actor_name,actor_role,module,entity,record_title,action,changed_fields").order("created_at", { ascending: false }).limit(150)
  ]); const errors = [customers.error, tasks.error, cases.error, invoices.error, employees.error, activity.error].filter(Boolean); setError(errors.map((item) => item.message).join(" · ")); setData({ customers: customers.data || [], tasks: tasks.data || [], cases: cases.data || [], invoices: invoices.data || [], employees: employees.data || [], activity: activity.data || [] }); setLoading(false); };
  useEffect(() => { load(); const timer = window.setInterval(load, 30000); return () => window.clearInterval(timer); }, []);
  const summary = useMemo(() => {
    const openTasks = data.tasks.filter((item) => item.title?.trim() && !CLOSED.has(item.status)).length;
    const activeCases = data.cases.filter((item) => !["Closed", "Disposed"].includes(item.status)).length;
    const outstanding = data.invoices.reduce((sum, item) => {
      const total = Number(item.total_amount || 0);
      const paid = Number(item.paid_amount || 0);
      return sum + Math.max(total - paid, 0);
    }, 0);
    const currentDay = new Date().toISOString().slice(0, 10);
    const today = data.activity.filter((item) => String(item.created_at).slice(0, 10) === currentDay);
    return { openTasks, activeCases, outstanding, today };
  }, [data]);
  return <div className="min-h-screen bg-slate-950 p-6 text-slate-100"><style>{css}</style><header className="panel mb-6 flex justify-between gap-4"><div><span className="tag">Firm command centre</span><h1 className="mt-2 text-2xl font-black">Operational Overview</h1><p className="mt-1 text-xs text-slate-400">Meaningful work changes by Principal Admins and Associates, refreshed every 30 seconds.</p></div><button className="button" onClick={load}>{loading ? "Refreshing…" : "Refresh dashboard"}</button></header>{error && <div className="alert">{error} Run firm-universal-audit.sql.</div>}<div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Active clients" value={data.customers.length} /><Metric label="Open tasks" value={summary.openTasks} /><Metric label="Active legal cases" value={summary.activeCases} /><Metric label="Today's activity" value={summary.today.length} /><Metric label="Outstanding fees" value={money.format(summary.outstanding)} /></div><div className="grid grid-cols-1 gap-6 xl:grid-cols-12"><section className="panel xl:col-span-8"><h2 className="heading">Today's work progress</h2><p className="hint mb-4">Includes created, updated, deleted, assigned, reminder, billing, tax, company, and litigation data changes.</p>{loading ? <Empty text="Loading activity…" /> : summary.today.length ? <div className="space-y-2">{summary.today.map((item) => <article key={item.id} className="activity"><div className="flex justify-between gap-3"><div><span className="badge">{item.module}</span><b className="ml-2 text-xs">{item.record_title}</b><p className="mt-2 text-[11px] text-slate-400">{item.action} {item.entity}{item.changed_fields?.length ? ` · changed: ${item.changed_fields.join(", ")}` : ""}</p></div><div className="text-right"><p className="text-xs font-bold">{item.actor_name}</p><p className="hint">{String(item.actor_role || "Firm user").replaceAll("_", " ")} · {time(item.created_at)}</p></div></div></article>)}</div> : <Empty text="No meaningful work changes were recorded today." />}</section><section className="panel xl:col-span-4"><h2 className="heading">Team workload snapshot</h2><div className="mt-4 space-y-4">{data.employees.filter((item) => item.employment_status !== "INACTIVE").map((item) => { const capacity = Number(item.max_capacity || 10); const active = Number(item.active_tasks || 0); return <div key={item.id}><div className="flex justify-between text-xs"><b>{item.full_name}</b><span>{active}/{capacity}</span></div><div className="bar"><div className="fill" style={{ width: `${Math.min(100, active / capacity * 100)}%` }} /></div></div>; })}</div></section></div></div>;
}
function Metric({ label, value }) { return <div className="metric"><p>{label}</p><strong>{value}</strong></div>; } function Empty({ text }) { return <div className="empty">{text}</div>; } function time(value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : date.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" }); }
const css = `.panel{background:#0f172a;border:1px solid #1e293b;border-radius:12px;padding:20px}.tag,.heading{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em;color:#a5b4fc}.heading{color:#94a3b8}.button{background:#1e293b;border:1px solid #334155;border-radius:7px;padding:10px 13px;font-size:11px;font-weight:800}.metric{background:#0f172a;border:1px solid #1e293b;border-left:4px solid #6366f1;border-radius:10px;padding:15px}.metric p,.hint{font-size:10px;color:#94a3b8}.metric strong{display:block;font-size:23px;margin-top:5px}.activity{background:#020617;border:1px solid #1e293b;border-radius:8px;padding:13px}.badge{font-size:9px;font-weight:800;padding:3px 6px;border-radius:4px;background:#172554;color:#bfdbfe}.bar{height:6px;background:#1e293b;border-radius:999px;margin-top:7px}.fill{height:100%;background:#10b981;border-radius:999px}.empty{border:1px dashed #334155;border-radius:8px;padding:35px;text-align:center;color:#64748b;font-size:12px}.alert{margin-bottom:14px;background:#4c0519;border:1px solid #881337;color:#fecdd3;border-radius:7px;padding:11px;font-size:12px}`;
